//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTRex.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualWorkout
    {
        public int ID { get; set; }
        public int TargetWorkoutID { get; set; }
        public int ActualNumSets { get; set; }
        public int ActualNumReps { get; set; }
        public System.DateTime Date { get; set; }
        public int TimeOfDayID { get; set; }
        public string WeightUsed { get; set; }
        public int PainLevelID { get; set; }
        public string ActualNotes { get; set; }
    
        public virtual PainLevel PainLevel { get; set; }
        public virtual TargetWorkout TargetWorkout { get; set; }
        public virtual TimeOfDay TimeOfDay { get; set; }
    }
}
